import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Theme Colors
        background: '#fcf8ff',
        'on-background': '#1b1b23',
        surface: '#fcf8ff',
        'surface-dim': '#dbd8e4',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2fe',
        'surface-container': '#efecf8',
        'surface-container-high': '#e9e6f3',
        'surface-container-highest': '#e4e1ed',
        'on-surface': '#1b1b23',
        'on-surface-variant': '#464554',
        'inverse-surface': '#303038',
        'inverse-on-surface': '#f2effb',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'surface-tint': '#494bd6',
        primary: '#4648d4',
        'on-primary': '#ffffff',
        'primary-container': '#6063ee',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#c0c1ff',
        secondary: '#8127cf',
        'on-secondary': '#ffffff',
        'secondary-container': '#9c48ea',
        'on-secondary-container': '#fffbff',
        tertiary: '#904900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b55d00',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#f0dbff',
        'secondary-fixed-dim': '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        'surface-variant': '#e4e1ed',

        // Active / AI states
        'active-lavender': '#B6B2FF',
        'active-cyan': '#8FE3FF',
        'active-silver': '#E0E0E0',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        display: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        headline: ['Plus Jakarta Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '20px',
        margin: '24px',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        card: '2rem', // Large organic card corners (Stitch lg)
        modal: '3rem', // Modal corners (Stitch xl)
      },
    },
  },
  plugins: [],
};
export default config;
